# Generated by Django 4.0.4 on 2022-06-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_lower',
            field=models.TextField(editable=False, max_length=200),
        ),
    ]
