# Generated by Django 4.0.4 on 2022-05-30 23:58

from django.db import migrations, models
import django.db.models.deletion
import plants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='name')),
                ('name_lower', models.CharField(editable=False, max_length=60, null=True, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=60, unique=True, verbose_name='URL')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='time create')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='time update')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Taxons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('slug', models.SlugField(editable=False, max_length=60, unique=True, verbose_name='URL')),
                ('order', models.IntegerField(choices=[(0, 'Domain'), (1, 'Supra-kingdom'), (2, 'Kingdom'), (3, 'Sub-kingdom'), (4, 'Clade'), (5, 'Supra-department'), (6, 'Department'), (7, 'Sub-department'), (8, 'Superclass'), (9, 'Class'), (10, 'Subclass'), (11, 'Superorder'), (12, 'Order'), (13, 'Series '), (14, 'Type'), (15, 'Family'), (16, 'Subfamily'), (17, 'Supertribe'), (18, 'Tribe'), (19, 'Subtribe'), (20, 'Genus'), (21, 'Subgenus'), (22, 'Section'), (23, 'Subsection'), (24, 'Grex'), (25, 'Natural hybrid'), (26, 'Kind'), (27, 'Variety'), (28, 'Subkind'), (29, 'Without rank')], default=0, verbose_name='rank')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='time create')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='time update')),
            ],
            options={
                'verbose_name': 'taxon',
                'verbose_name_plural': 'taxons',
                'ordering': ('name',),
                'unique_together': {('order', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('name_lower', models.CharField(editable=False, max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, upload_to=plants.models.content_file_name, verbose_name='image')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='time create')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='time update')),
                ('categories', models.ManyToManyField(blank=True, to='plants.categories', verbose_name='categories')),
                ('taxons', models.ManyToManyField(blank=True, to='plants.taxons', verbose_name='taxons')),
            ],
            options={
                'verbose_name': 'plant',
                'verbose_name_plural': 'plants',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=64, verbose_name='category')),
                ('text', models.TextField(blank=True, verbose_name='description')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='time create')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='time update')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plants', verbose_name='plant')),
            ],
            options={
                'verbose_name': 'description',
                'verbose_name_plural': 'descriptions',
                'ordering': ('category',),
                'unique_together': {('plant', 'category')},
            },
        ),
    ]
