# Generated by Django 4.0.4 on 2022-06-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name_lower',
            field=models.CharField(editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='descriptions',
            name='category',
            field=models.CharField(blank=True, max_length=255, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='plants',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='plants',
            name='name_lower',
            field=models.CharField(editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='taxons',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='taxons',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
